Document: zsnapper
Title: Debian zsnapper Manual
Author: <insert document author here>
Abstract: This manual describes what zsnapper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zsnapper/zsnapper.sgml.gz

Format: postscript
Files: /usr/share/doc/zsnapper/zsnapper.ps.gz

Format: text
Files: /usr/share/doc/zsnapper/zsnapper.text.gz

Format: HTML
Index: /usr/share/doc/zsnapper/html/index.html
Files: /usr/share/doc/zsnapper/html/*.html
